version: 2

project_name: phantom

builds:
- id: phantom
  main: ./cmd/phantom
  binary: phantom
  env:
  - CGO_ENABLED=0
  goos: [ linux, darwin, windows ]
  goarch: [ amd64, arm64 ]
  ignore:
  - goos: windows
    goarch: arm64

archives:
- id: default
  name_template: >-
    {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
  formats:
  - tar.gz
  format_overrides:
  - goos: windows
    formats: [ zip ]
  files:
  - README.md
  - LICENSE*

checksum:
  name_template: checksums.txt

changelog:
  use: git
